cluster_name: demo.mapr.com
customer_name: MapR PS
output_dir: /Users/chufe/clustercheck
mapr_user: mapr

nodes:
  - host: 10.0.0.24
    ssh_user: ec2-user
    ssh_identity: '/Users/chufe/.ssh/id_rsa'
    roles:
       - datacenter1
       - clusterjob-execution
  - host: 10.0.0.167
    ssh_user: ec2-user
    ssh_identity: '/Users/chufe/.ssh/id_rsa'
    roles:
      - datacenter1
  - host: 10.0.0.239
    ssh_user: ec2-user
    ssh_identity: '/Users/chufe/.ssh/id_rsa'
    roles:
      - datacenter1

modules:
  clusteraudit:
    enabled: true
    role: datacenter1
  benchmark-network-iperf:
    enabled: true
    tests:
    - threads: 1
      dataPerThread: 4096M
  benchmark-maprfs-dfsio:
    enabled: true
    role: clusterjob-execution
  benchmark-maprfs-rwtest:
    enabled: true
    tests:
    - volume_type: standard
      compression: 'off'
      topology: /data
      sizeInMB: 8192
      replication: 3
    - volume_type: standard
      compression: 'on'
      topology: /data
      sizeInMB: 8192
      replication: 3
    - volume_type: local
      compression: 'off'
      use_disk_percentage: 5
    - volume_type: local
      compression: 'on'
      use_disk_percentage: 5