cluster_name: demo.mapr.com
customer_name: Your company name
output_dir: /path/for/results
mapr_user: mapr
nodes:
- host: hostname1.fqdn
  ssh_user: sshuser
  ssh_identity: /home/user/.ssh/id_rsa
  roles:
  - clusterjob-execution
- host: hostname2.fqdn
  ssh_user: sshuser
  ssh_identity: /home/user/.ssh/id_rsa
- host: hostname3.fqdn
  ssh_user: sshuser
  ssh_identity: /home/user/.ssh/id_rsa
modules:
  benchmark-maprfs-rwtest:
    enabled: true
    tests:
    - volume: standard
      compression: 'off'
      topology: /data
      sizeInMB: 16384
      replication: 3
    - volume: standard
      compression: 'on'
      topology: /data
      sizeInMB: 16384
      replication: 3
    - volume: local
      compression: 'off'
      useDiskPercentage: 5
    - volume: local
      compression: 'on'
      useDiskPercentage: 5
