cluster_name: demo.mapr.com
customer_name: Your company name
output_dir: /path/for/results
mapr_user: mapr
nodes:
- host: hostname1.fqdn
  ssh_user: sshuser
  ssh_identity: /home/user/.ssh/id_rsa
  roles:
  - clusterjob-execution
- host: hostname2.fqdn
  ssh_user: sshuser
  ssh_identity: /home/user/.ssh/id_rsa
- host: hostname3.fqdn
  ssh_user: sshuser
  ssh_identity: /home/user/.ssh/id_rsa
modules:
  benchmark-yarn-terasort-mr:
    enabled: true
    role: clusterjob-execution
    chunkSizeInMB: 1
    dataSizeInMB: 1048576
    topology: /data
    replication: 1
