cluster_name: demo.mapr.com
customer_name: Your company name
output_dir: /path/for/results
mapr_user: mapr
nodes:
- host: hostname1.fqdn
  ssh_user: sshuser
  ssh_identity: /home/user/.ssh/id_rsa
  roles:
  - clusterjob-execution
- host: hostname2.fqdn
  ssh_user: sshuser
  ssh_identity: /home/user/.ssh/id_rsa
- host: hostname3.fqdn
  ssh_user: sshuser
  ssh_identity: /home/user/.ssh/id_rsa
modules:
  clusteraudit:
    enabled: true
    testprop: sampleVal
  benchmark-network-iperf:
    enabled: true
    tests:
    - threads: 1
      dataPerThread: 4096M
    - threads: 2
      dataPerThread: 2048M
    - threads: 4
      dataPerThread: 1024M
    - threads: 8
      dataPerThread: 512M
  benchmark-maprfs-dfsio:
    enabled: true
    role: clusterjob-execution
    dfsioFilesPerDisk: 1
    dfsioFileSizeInMB: 8196
    topology: /data
    replication: 1
  benchmark-maprfs-rwtest:
    enabled: true
    tests:
    - volume_type: standard
      compression: 'off'
      topology: /data
      size_in_mb: 16384
      replication: 3
      threads: 1
    - volume_type: standard
      compression: 'on'
      topology: /data
      size_in_mb: 16384
      replication: 3
      threads: 1
    - volume_type: local
      compression: 'off'
      use_disk_percentage: 5
    - volume_type: local
      compression: 'on'
      use_disk_percentage: 5
