cluster_name: demo.mapr.com
customer_name: Your company name
output_dir: /path/for/results
mapr_user: mapr
nodes-global-config:
  disks:
  - /dev/nvme1n1
  - /dev/nvme2n1
  - /dev/nvme3n1
  ssh_user: ec2-user
  ssh_identity: /Users/chufe/.ssh/id_rsa
  ssh_port: 22
nodes:
- host: hostname1.fqdn
  roles:
  - clusterjob-execution
- host: hostname2.fqdn
- host: hostname3.fqdn
  ssh_user: different_user
  ssh_identity: /home/user/.ssh/different_key
  ssh_port: 22222
modules:
  cluster-audit:
    enabled: true
    mapruser: mapr
  cluster-config-audit:
    enabled: true
  benchmark-rawdisk:
    enabled: true
    tests:
    - mode: READONLY
      data_in_mb: 4096
    disks:
    - /dev/sdb
    - /dev/sdc
    - /dev/sdd
  benchmark-memory:
    enabled: true
  benchmark-network-iperf:
    enabled: true
    tests:
    - threads: 1
      data_per_thread: 4096M
      mode: split
    - threads: 2
      data_per_thread: 2048M
      mode: split
    - threads: 4
      data_per_thread: 1024M
      mode: split
    - threads: 8
      data_per_thread: 512M
      mode: split
  benchmark-maprfs-dfsio:
    enabled: true
    role: clusterjob-execution
    tests:
    - dfsio_number_of_files: 1024
      dfsio_file_size_in_mb: 8196
      topology: /data
      replication: 1
      compression: 'on'
  benchmark-maprfs-rwtest:
    enabled: true
    tests:
    - volume_type: standard
      compression: 'off'
      topology: /data
      size_in_mb: 16384
      replication: 3
      threads: 1
    - volume_type: standard
      compression: 'on'
      topology: /data
      size_in_mb: 16384
      replication: 3
      threads: 1
    - volume_type: local
      compression: 'off'
      use_disk_percentage: 5
    - volume_type: local
      compression: 'on'
      use_disk_percentage: 5
  benchmark-yarn-terasort-mr:
    enabled: true
    role: clusterjob-execution
    tests:
    - chunk_size_in_mb: 256
      rows: 10000000000
      rows_comment: one row has 100 byte
      reduce_tasks_per_node: 2
      topology: /data
      replication: 3
      compression: 'on'
  benchmark-yarn-terasort-spark:
    enabled: true
    role: clusterjob-execution
    tests:
    - chunk_size_in_mb: 256
      data_size: 1T
      num_executors: 10
      executor_cores: 2
      executor_memory: 4G
      topology: /data
      replication: 3
      compression: 'on'
